allowBuilds:
  esbuild: true
autoInstallPeers: true
engineStrict: true
ignoreScripts: true
lockfileIncludeTarballUrl: true
minimumReleaseAge: 4320
preferFrozenLockfile: true
private: true
resolutionMode: highest
saveExact: true
strictPeerDependencies: true
strictSsl: true
verifyStoreIntegrity: true
